version: "3"

volumes:
  pgdata:


services:
  postgres:
    image: "postgres:16"
    restart: always
    environment:
      - POSTGRES_PASSWORD=localpasswd
      - TZ=UTC
      - PGTZ=UTC
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - PGPASSWORD=localpasswd
    depends_on:
      postgres:
        condition: service_healthy
